// swiftlint:disable:next unused_import - Foundation provides exit(_:)
import Foundation

gestureRulesTests()
gestureHoldsTests()
bindingsTests()
bindingClashTests()
keyCombinationsTests()
glideCurveTests()
pixelAccumulatorTests()
statusTests()
actionsTests()
navigationTests()
inputEventsTests()
cecLogTests()
sessionReplayTests()
cecLinkTests()
systemShortcutsTests()

exit(Expect.summarize())
